config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/post' => 'posts#new'

  post '/post' => 'posts#create'

  get '/logout' => 'sessions#destroy'

  get '/home' => 'users#index'

  get '/' => 'home#index'

  get '/signup' =>  'users#new'

  get 'users/create'

  get 'users/show'

  get '/welcome/' => 'users#welcome'

  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	  	if session[:user_id].nil?	 
			redirect_to '/welcome' 
		else
			@user = User.find(session[:user_id])
  		end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create

	  current_user = User.find(session[:user_id])

        post = Post.new(post_params.merge(user_id: current_user.id))
	if post.save
		redirect_to '/'
        else
	        redirect_to new_post_path
        end
  end

  def index
  end

  private

  def post_params
	    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	  puts params
	  
	  @user = User.find_by(email: params[:email])
		
	  puts "PRINTING USER"
	  puts @user
	  if @user && @user.password == params[:password]
		  session[:user_id] = @user.id
		  redirect_to '/'
	  else
		  flash[:error] = "LOGIN UNSUCCESSFUL"
		  redirect_to '/login'
	  end
  end

  def destroy
	session[:user_id] = nil 
	redirect_to '/welcome'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	  @user = User.find(session[:user_id])
  end

  def new
	  @user = User.new
  end

  def show
#	@user = User.find(params[:id])
#	@posts = @user.posts.all
#	@post = Post.new
#	@current_user = User.find(session[:user_id])
        post = Post.new(posts_params.merge(user_id: current_user.id))
	        if post.save
			redirect_to '/'
	        else
	                redirect_to new_post_path
	        end
  end

  def create
  @user = User.create(user_params)
    if @user.save
      redirect_to '/welcome'
      session[:user_id] = @user.id
    else
      flash[:notice] = "Please fill out all forms!"
      redirect_to '/users/new' 
    end
  end

  private

  def user_params
	params.require(:user).permit(:email, :password, :name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>WELCOME TO MY BLOG</h1>
<%= link_to "LOGOUT", logout_path %>

<%= @user.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for :post, url: {action: :create}  do |f| %>
	<%= f.text_field :title %>
	<%= f.text_area :body %>
	<%= f.submit 'Submit'%>
<%end%> 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>WELCOME TO MY BLOG</h1>
<%= @user.password %>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
	Email: <%= form.email_field :email %>
	Password: <%= form.password_field :password %>
	Name: <%= form.text_field :name %>
	<%= form.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<%= @user.email %>

<%= form_for :post, url: {action: :create}  do |f| %>
   <%= f.text_field :title %>
   <%= f.text_area :body %>
   <%= f.submit 'Submit'%>
<%end%> 

app/views/users/welcome.html.erb
WELCOME <%= session[:user_id] %>

<%= link_to 'signup', signup_path %>
<%= link_to 'login', login_path %>